### ISSUE TITLE
Should we create a `red-hat` style

### ISSUE THREAD

**Issue by rolfedh** [rolfedh/studious-fortnight#2]
Should we rename the Che style to "Red-Hat"?

**Comment by rolfedh** [comment]
@themr0c what do you think?

**Comment by Gerry-Forde** [comment]
@rolfedh I presume we can use sub-folders for style rules, so if we did rename Che to "RedHat", we could have something like:
|styles
    ├───Red-Hat
    │   ├───CheDocs
    │   ├───SupplementaryStyleGuide
    │   ├───ModularDocs
    │   └───IBM-Quickstart-Reference
    └───IBM

**Comment by rolfedh** [comment]
@Gerry-Forde: I just had a conversation with Ingrid Towey, who suggested adding the "CCS" qualifier to "Red-Hat" so we get "Red-Hat-CCS." This distinction will help make the scope of these Vale style rules clearer to non-CCS users at Red Hat. 

At some point in the future, if we begin covering non-CCS use cases, we can remove "-CCS" from the style folder or some other similar solution.
