### ISSUE TITLE
Vale cannot handle parenthesis in search terms

### ISSUE THREAD

**Issue by aireilly** [rolfedh/studious-fortnight#35]
The SSG has a number of word usage guidance items that includes parenthesis. Vale does not like parenthesis in search terms, and doesn't seem to be able to search for the escaped characters, for example `\(` or `\)`. 

Example rule `red-hat-network-satellite-server.yml`:

```
extends: substitution
message: "Use '%s' instead of '%s'."
link: https://redhat-documentation.github.io/supplementary-style-guide/#red-hat-network-satellite-server
ignorecase: true
level: error
action:
  name: replace
source: Red Hat
swap:
    Red Hat Satellite (Server) : Red Hat Network Satellite Server
```

**Comment by aireilly** [comment]
In Atom, the following error is displayed: 

```
E201 Invalid value provided [/home/kquinn/openshift-docs/.vale/styles/Red-Hat-CCS/SupplementaryStyleGuide/red-hat-network-proxy-server.yml:10:5]:

   9  swap:
  10*     Red Hat Proxy (Server) : Red Hat Network Proxy Server

capture group not supported; use '(?:' instead of '('

Execution stopped with code 1.
```

**Comment by aireilly** [comment]
Need to do this: 

"You need to use Red Hat Proxy \(Server\) and then set nonword: true to drop the word boundaries (\b)."

From jdkato on Vale slack 😎

**Comment by themr0c** [comment]
This parenthesis is quite ambiguous. As I understand it, it does not mean than we have to search for th" "Red Hat Satellite (Server)" string but for the string: "Red Hat Satellite" or "Red Hat Satellite Server". Correct search string should be, then:

```
    Red Hat Satellite|Red Hat Satellite Server : Red Hat Network Satellite Server
```

**Comment by aireilly** [comment]
I think we can close this.
